### ISSUE TITLE
Port Wine fix from DCS codebase for ` System.NotImplementedException on IAudioEndpointVolume.GetChannelCount` 

### ISSUE THREAD

**Issue by raven-intheclouds** [ciribob/IL2-SimpleRadioStandalone#29]
Hi,

Trying IL2-SR-ClientRadio.exe by following the steps for the DCS codebase.

It installs and starts fine, but trying the "audio preview" button gives me an error pop-up, and the logs show:
```
2024-03-04 20:25:30.5722 | Ciribob.IL2.SimpleRadio.Standalone.Client.Audio.AudioPreview | Error starting audio Input - Quitting! The method or operation is not implemented. System.NotImplementedException: The method or operation is not implemented.
   at NAudio.CoreAudioApi.Interfaces.IAudioEndpointVolume.GetChannelCount(Int32& pnChannelCount)
   at NAudio.CoreAudioApi.AudioEndpointVolumeChannels..ctor(IAudioEndpointVolume parent) in F:\Dropbox\Dev\Personal\IL2-SimpleRadioStandalone\NAudio\CoreAudioApi\AudioEndpointVolumeChannels.cs:line 63
   at NAudio.CoreAudioApi.AudioEndpointVolume..ctor(IAudioEndpointVolume realEndpointVolume) in F:\Dropbox\Dev\Personal\IL2-SimpleRadioStandalone\NAudio\CoreAudioApi\AudioEndpointVolume.cs:line 160
   at NAudio.CoreAudioApi.MMDevice.GetAudioEndpointVolume() in F:\Dropbox\Dev\Personal\IL2-SimpleRadioStandalone\NAudio\CoreAudioApi\MMDevice.cs:line 90
   at Ciribob.IL2.SimpleRadio.Standalone.Client.Audio.AudioPreview.StartPreview(Boolean windowsN)
```

I have dotnet 4.8 installed, and everything seems fine. I also removed a Logitech webcam just in case.

Hence maybe porting the fix shown [here](https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/621#issuecomment-1239702000) into the IL2 codebase may fix it.

Here is the full clientlog.txt:

<details>
<summary>Click to expand</summary>

```
2024-03-04 20:29:52.5724 | IL2_SR_Client.App | Arguments: 
2024-03-04 20:29:52.5802 | IL2_SR_Client.App | Z:\home\deck\Games\IL2\gamefiles\SRS\IL2-SR-ClientRadio.exe 
2024-03-04 20:29:52.6001 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.ProfileSettingsStore | No need to migrate - migration complete 
2024-03-04 20:29:53.4877 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Saved ID default 
2024-03-04 20:29:54.0326 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - 12 audio input devices available, configuring as usual 
2024-03-04 20:29:54.0417 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Monitor of Plantronics Blackwire 3220 Series Analog Stereo {0.0.1.00000000}.{11B165A7-0CD0-4C19-B36B-20E55A7734EB} - Name GUIDMonitor of Plantronics Blackwire 3220 Series Analog Stereo 
2024-03-04 20:29:54.0452 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Monitor of Vanatoo T0 Digital Stereo (IEC958) {0.0.1.00000000}.{1A90BBF9-FB88-40D3-A9F5-E4444A2E8B13} - Name GUIDMonitor of Vanatoo T0 Digital Stereo (IEC958) 
2024-03-04 20:29:54.0488 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - PulseAudio {0.0.1.00000000}.{25DA76D0-033C-4235-9002-19F48894AC6F} - Name GUIDPulseAudio 
2024-03-04 20:29:54.0524 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Monitor of Rembrandt Radeon High Definition Audio Controller {0.0.1.00000000}.{7E7A01D2-608E-413B-A57A-2FF9D8541FE1} - Name GUIDMonitor of Rembrandt Radeon High Definition Audio Controller 
2024-03-04 20:29:54.0555 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Plantronics Blackwire 3220 Series Analog Stereo {0.0.1.00000000}.{7F065AE6-C101-4E70-9FCD-0FBB1CAE465E} - Name GUIDPlantronics Blackwire 3220 Series Analog Stereo 
2024-03-04 20:29:54.0588 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Monitor of ACP/ACP3X/ACP6x Audio Coprocessor Speaker {0.0.1.00000000}.{8430B12A-91DB-411C-A3F9-01DAE62EB7C6} - Name GUIDMonitor of ACP/ACP3X/ACP6x Audio Coprocessor Speaker 
2024-03-04 20:29:54.0619 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Monitor of ACP/ACP3X/ACP6x Audio Coprocessor Headphones {0.0.1.00000000}.{8839DADC-4DD4-4A2D-9F7F-90495DAF2471} - Name GUIDMonitor of ACP/ACP3X/ACP6x Audio Coprocessor Headphones 
2024-03-04 20:29:54.0650 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Virtual Source {0.0.1.00000000}.{AA3C982D-5206-4941-9C7E-4C59DBD6D032} - Name GUIDVirtual Source 
2024-03-04 20:29:54.0683 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - ACP/ACP3X/ACP6x Audio Coprocessor {0.0.1.00000000}.{AE7D2982-EEB6-4A73-A1B9-D1F4CB135692} - Name GUIDACP/ACP3X/ACP6x Audio Coprocessor 
2024-03-04 20:29:54.0714 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Filter Chain Source {0.0.1.00000000}.{C8B40C66-CC2C-40F2-8EF4-0D2373AFFDB2} - Name GUIDFilter Chain Source 
2024-03-04 20:29:54.0745 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Monitor of Virtual Sink {0.0.1.00000000}.{D772A643-FAD1-492C-BB21-EE105A85190A} - Name GUIDMonitor of Virtual Sink 
2024-03-04 20:29:54.0776 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioInputSingleton | Audio Input - Monitor of Filter Chain Sink {0.0.1.00000000}.{DFC3D09E-C2E4-49FD-966C-93D4FCC9A94C} - Name GUIDMonitor of Filter Chain Sink 
2024-03-04 20:29:54.1747 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Windows N Detected - using inbuilt resampler 
2024-03-04 20:29:54.1747 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Building Normal Audio Outputs 
2024-03-04 20:29:54.1747 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Saved ID default 
2024-03-04 20:29:54.1807 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Virtual Sink {0.0.0.00000000}.{04774D0C-F1DB-4055-8DBB-60168558E601} CHN:2 Rate:48000 
2024-03-04 20:29:54.1828 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Plantronics Blackwire 3220 Series Analog Stereo {0.0.0.00000000}.{39F1CF13-6C19-48F6-AE17-A8385550B59A} CHN:2 Rate:48000 
2024-03-04 20:29:54.1849 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Filter Chain Sink {0.0.0.00000000}.{5C5AF705-58D1-4A81-BE53-7BF47B4CDE2C} CHN:2 Rate:48000 
2024-03-04 20:29:54.1873 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Rembrandt Radeon High Definition Audio Controller {0.0.0.00000000}.{5C6C8FD1-B81E-4978-8C5D-87833D2884E8} CHN:2 Rate:48000 
2024-03-04 20:29:54.1890 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Vanatoo T0 Digital Stereo (IEC958) {0.0.0.00000000}.{6FBAC1F7-6EA4-48D1-874A-E13C35013BF0} CHN:2 Rate:48000 
2024-03-04 20:29:54.1910 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - ACP/ACP3X/ACP6x Audio Coprocessor Speaker {0.0.0.00000000}.{DDB98E48-B520-4467-8301-6CD8FBADADC0} CHN:2 Rate:48000 
2024-03-04 20:29:54.1926 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - ACP/ACP3X/ACP6x Audio Coprocessor Headphones {0.0.0.00000000}.{EC041888-6C05-4423-A570-C5C5E5BBDBFB} CHN:2 Rate:48000 
2024-03-04 20:29:54.1944 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - PulseAudio {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} CHN:2 Rate:48000 
2024-03-04 20:29:54.1962 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Building Microphone Audio Outputs 
2024-03-04 20:29:54.1962 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Mic Audio Output - Saved ID  
2024-03-04 20:29:54.1968 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Virtual Sink {0.0.0.00000000}.{04774D0C-F1DB-4055-8DBB-60168558E601} CHN:2 Rate:48000 
2024-03-04 20:29:54.1993 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Plantronics Blackwire 3220 Series Analog Stereo {0.0.0.00000000}.{39F1CF13-6C19-48F6-AE17-A8385550B59A} CHN:2 Rate:48000 
2024-03-04 20:29:54.2014 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Filter Chain Sink {0.0.0.00000000}.{5C5AF705-58D1-4A81-BE53-7BF47B4CDE2C} CHN:2 Rate:48000 
2024-03-04 20:29:54.2032 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Rembrandt Radeon High Definition Audio Controller {0.0.0.00000000}.{5C6C8FD1-B81E-4978-8C5D-87833D2884E8} CHN:2 Rate:48000 
2024-03-04 20:29:54.2049 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - Vanatoo T0 Digital Stereo (IEC958) {0.0.0.00000000}.{6FBAC1F7-6EA4-48D1-874A-E13C35013BF0} CHN:2 Rate:48000 
2024-03-04 20:29:54.2074 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - ACP/ACP3X/ACP6x Audio Coprocessor Speaker {0.0.0.00000000}.{DDB98E48-B520-4467-8301-6CD8FBADADC0} CHN:2 Rate:48000 
2024-03-04 20:29:54.2091 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - ACP/ACP3X/ACP6x Audio Coprocessor Headphones {0.0.0.00000000}.{EC041888-6C05-4423-A570-C5C5E5BBDBFB} CHN:2 Rate:48000 
2024-03-04 20:29:54.2108 | Ciribob.IL2.SimpleRadio.Standalone.Client.Singletons.AudioOutputSingleton | Audio Output - PulseAudio {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} CHN:2 Rate:48000 
2024-03-04 20:29:55.7651 | Ciribob.IL2.SimpleRadio.Standalone.Client.UI.MainWindow | Window visibility check is disabled, skipping 
2024-03-04 20:29:55.7651 | Ciribob.IL2.SimpleRadio.Standalone.Client.UI.MainWindow | Started IL2-SimpleRadio Client 1.0.2.0 
2024-03-04 20:29:55.8770 | Ciribob.IL2.SimpleRadio.Standalone.Client.UI.MainWindow | default - Profile now in use 
2024-03-04 20:29:55.9069 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Attempt to Load Whitelist from Z:\home\deck\Games\IL2\gamefiles\SRS\whitelist.txt 
2024-03-04 20:29:55.9081 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | File doesnt exist: Z:\home\deck\Games\IL2\gamefiles\SRS\whitelist.txt 
2024-03-04 20:29:55.9083 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Attempt to Load Blacklist from Z:\home\deck\Games\IL2\gamefiles\SRS\blacklist.txt 
2024-03-04 20:29:55.9083 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | File doesnt exist: Z:\home\deck\Games\IL2\gamefiles\SRS\blacklist.txt 
2024-03-04 20:29:55.9198 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Starting Device Search. Expand Search: False 
2024-03-04 20:29:55.9446 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Found Device ID:6f1d2b60-d5a0-11cf-bfc7-444553540000 Wine Mouse Usage: Undefined Type: Mouse 
2024-03-04 20:29:55.9446 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Adding Device ID:6f1d2b60-d5a0-11cf-bfc7-444553540000 Wine Mouse 
2024-03-04 20:29:55.9547 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Found Device ID:6f1d2b61-d5a0-11cf-bfc7-444553540000 Wine Keyboard Usage: Undefined Type: Keyboard 
2024-03-04 20:29:55.9547 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Adding Device ID:6f1d2b61-d5a0-11cf-bfc7-444553540000 Wine Keyboard 
2024-03-04 20:29:55.9604 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Found Device ID:0126231d-0000-0000-0000-504944564944 VKB-Sim (C) Alex Oz 2023 VKBSim Space Gunfighter Usage: Generic Type: Gamepad 
2024-03-04 20:29:55.9684 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Adding ID:0126231d-0000-0000-0000-504944564944 VKB-Sim (C) Alex Oz 2023 VKBSim Space Gunfighter 
2024-03-04 20:29:55.9684 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Found Device ID:0211231d-0000-0000-0000-504944564944 VKB-Sim © Alex Oz 2021 VKBsim Gladiator EVO L THQ Usage: Generic Type: Joystick 
2024-03-04 20:29:55.9729 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Adding ID:0211231d-0000-0000-0000-504944564944 VKB-Sim © Alex Oz 2021 VKBsim Gladiator EVO L THQ 
2024-03-04 20:29:55.9731 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Found Device ID:120528de-0000-0000-0000-504944564944 Steam Deck Usage: Generic Type: Gamepad 
2024-03-04 20:29:55.9782 | Ciribob.IL2.SimpleRadio.Standalone.Client.Settings.InputDeviceManager | Adding ID:120528de-0000-0000-0000-504944564944 Steam Deck 
2024-03-04 20:29:56.0069 | Ciribob.IL2.SimpleRadio.Standalone.Client.CachedAudioEffect | Read Effect RADIO_TX from Z:\home\deck\Games\IL2\gamefiles\SRS\\AudioEffects\Radio-TX-1600.wav Successfully 
2024-03-04 20:29:56.0073 | Ciribob.IL2.SimpleRadio.Standalone.Client.CachedAudioEffect | Read Effect RADIO_RX from Z:\home\deck\Games\IL2\gamefiles\SRS\\AudioEffects\Radio-RX-1600.wav Successfully 
2024-03-04 20:29:57.8938 | Ciribob.IL2.SimpleRadio.Standalone.Common.UpdaterChecker | Running latest stable version: 1.0.2.0 
2024-03-04 20:29:58.8985 | Ciribob.IL2.SimpleRadio.Standalone.Client.Audio.AudioPreview | Error starting audio Input - Quitting! The method or operation is not implemented. System.NotImplementedException: The method or operation is not implemented.
   at NAudio.CoreAudioApi.Interfaces.IAudioEndpointVolume.GetChannelCount(Int32& pnChannelCount)
   at NAudio.CoreAudioApi.AudioEndpointVolumeChannels..ctor(IAudioEndpointVolume parent) in F:\Dropbox\Dev\Personal\IL2-SimpleRadioStandalone\NAudio\CoreAudioApi\AudioEndpointVolumeChannels.cs:line 63
   at NAudio.CoreAudioApi.AudioEndpointVolume..ctor(IAudioEndpointVolume realEndpointVolume) in F:\Dropbox\Dev\Personal\IL2-SimpleRadioStandalone\NAudio\CoreAudioApi\AudioEndpointVolume.cs:line 160
   at NAudio.CoreAudioApi.MMDevice.GetAudioEndpointVolume() in F:\Dropbox\Dev\Personal\IL2-SimpleRadioStandalone\NAudio\CoreAudioApi\MMDevice.cs:line 90
   at Ciribob.IL2.SimpleRadio.Standalone.Client.Audio.AudioPreview.StartPreview(Boolean windowsN)
```

</details>

Many thanks in advance!

**Comment by raven-intheclouds** [comment]
Also, I have run the DCS SRS under the same Wine prefix I installed IL-2-SRS (with dotnet 4.8, dx9) and the audio preview works fine. Hence, I expect this backport to work.

**Comment by raven-intheclouds** [comment]
Built IL-2 SRS on a Windows VM with the wine fix by commenting those 4 lines and I can confirm IL-2 SRS Client works fine:
https://github.com/raven-intheclouds/IL2-SimpleRadioStandalone/releases/tag/1.0.2.0-winefix

**Comment by JJones780** [comment]
Thanks for compiling this. I look forward to giving SRS a try on Linux.
Your compiled version says it needs Dotnet 4.8.1   which [WineHQ reports](https://appdb.winehq.org/objectManager.php?sClass=application&iId=2586) as garbage ( whereas 4.8 is Platinum )
Did you manually install 4.8.1 ?  Wine / Winetricks only offers up to 4.8 ?
Thanks

**Comment by JJones780** [comment]
I **changed the 4.8.1 to 4.8 in the  IL2-SR-ClientRadio.exe.config** and it's starting now.
The edited line now reads:

```
  <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>
```


For others, here's the quick route to install in a separate wine prefix (aka bottle ). Adapted from the [post here](https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/621).
The first line will create a new prefix at the WINEPREFIX location if it doesn't yet exist.
```
WINEPREFIX=/path/to/srs/prefix winecfg -v win10
WINEPREFIX=/path/to/srs/prefix winetricks -q dotnet48 corefonts
WINEPREFIX=/path/to/srs/prefix wine reg ADD 'HKCU\Software\Wine\DllOverrides' '/f' '/v' 'd3d9' '/t' 'REG_SZ' '/d' 'native'
```
cd to your IL-2_client_wine_fix_1.0.2 directory.
Make sure you changed the 4.8.1 to 4.8 in IL2-SR-ClientRadio.exe.config
... and run via 
`WINEPREFIX=/path/to/srs/prefix wine IL2-SR-ClientRadio.exe`

I'm assuming I need to manually edit the data/startup.cfg in the IL2 game directory ( running from its own proton wine prefix ) as stated in [client setup here](https://github.com/ciribob/IL2-SimpleRadioStandalone/wiki).

**Tested.. works! Neat!
I did NOT need to edit the data/startup.cfg - the settings were already present.**

**Comment by raven-intheclouds** [comment]
@JJones780 after some extensive use, I have realized that IL2-SRS has a memory leak that brings my system down and/or OOM kills things. I'm able to 100% hit it after playing for ~1h, with ram usage going to ~11GB and 6GB of zram (I'm playing on a docked Steamdeck, which has 12GB of ram..).

I wonder if it has to do with my crude patch (that has commented lines but not deleted variables, that may get instantiated again and again), or the compilation against 4.8.1 and then running it as 4.8.

Or maybe it's just SRS that has a memleak. I doubt that people are running IL-2 / DCS + SRS on a system with only 12GB of RAM as I do.

**Comment by JJones780** [comment]
It would be interesting to find the leak.. but as you say it could be in a multitude of places. Odds are it's elsewhere.

**Comment by BrianNormant** [comment]
> I **changed the 4.8.1 to 4.8 in the IL2-SR-ClientRadio.exe.config** and it's starting now. The edited line now reads:
> 
> ```
>   <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>
> ```
> 
> For others, here's the quick route to install in a separate wine prefix (aka bottle ). Adapted from the [post here](https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/621). The first line will create a new prefix at the WINEPREFIX location if it doesn't yet exist.
> 
> ```
> WINEPREFIX=/path/to/srs/prefix winecfg -v win10
> WINEPREFIX=/path/to/srs/prefix winetricks -q dotnet48 corefonts
> WINEPREFIX=/path/to/srs/prefix wine reg ADD 'HKCU\Software\Wine\DllOverrides' '/f' '/v' 'd3d9' '/t' 'REG_SZ' '/d' 'native'
> ```
> 
> cd to your IL-2_client_wine_fix_1.0.2 directory. Make sure you changed the 4.8.1 to 4.8 in IL2-SR-ClientRadio.exe.config ... and run via `WINEPREFIX=/path/to/srs/prefix wine IL2-SR-ClientRadio.exe`
> 
> I'm assuming I need to manually edit the data/startup.cfg in the IL2 game directory ( running from its own proton wine prefix ) as stated in [client setup here](https://github.com/ciribob/IL2-SimpleRadioStandalone/wiki).
> 
> **Tested.. works! Neat! I did NOT need to edit the data/startup.cfg - the settings were already present.**

Following this I managed to run the client, The issue i'm having is that IL-2 Doesn't seem to ever connect with the client, I guess this could be some wayland related problem? I'm sure which method this client use to communicate with the il2 process.

Did you do anything in particular to have both run the client and IL on linux?

Edit: Nevermind, Turn out I didn't read everything, I tried to run the installer with wine but it crashed so I assumed the `data/startup.cfg` was edited but I was wrong
